Extensions of QRNN code.
atmtools/typhon pull request #369
Opened 2020-09-28 06:26 UTC by simonpf

This extends the current implementation of QRNN to support both Pytorch and Keras
as backends. The QRNN class has been refactored to separate general QRNN functionality
from the underlying neural network model. Some functionality has been added e.g. computing
the posterior mean and sampling from a fitted Gaussian.

This work is part of an upcoming study on cloud correction at 183 GHz.

2020-09-29 09:22 UTC, olemke commented on doc/typhon.retrieval.qrnn.rst
> +automatically use the one the is available on your system. If both are available
Typo: the one *that* is

2020-09-29 09:32 UTC, olemke commented on doc/typhon.retrieval.qrnn.rst
> +.. currentmodule:: typhon.retrieval.qrnn.models.pytorch
These should be `*.keras` instead of `*.pytorch` which is already documentated above.

2020-09-29 09:36 UTC, olemke requested changes
Just fix the two minor issues I mentioned and it's ok to merge from my side.

2020-09-30 09:22 UTC, simonpf commented
Thank you for the suggestions! Fixed!

2020-09-30 09:53 UTC, lkluft approved these changes
Looks good 👍

2020-09-30 10:43 UTC, olemke approved these changes

2020-09-30 10:43 UTC, merged